openapi: 3.0.2
info:
  title: Pi-hole API
  version: "6.0"
  description: >
    The Pi-hole API is organized around [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer).
    Our API has predictable resource-oriented URLs, accepts and returns reliable UTF-8 [JavaScript Object Notation (JSON)-encoded](http://www.json.org/) data for all API responses, and uses standard HTTP response codes and verbs.

    Most (but not all) endpoints require authentication.
    API endpoints requiring authentication will fail with code `401 Unauthorized` when used outside a valid session.
servers:
  - url: http://pi.hole:8080/api/
  - url: 'http://{url}:{port}/{path}/'
    variables:
      url:
        description: URL or address of your Pi-hole
        default: pi.hole
      port:
        description: Port of your Pi-hole's API
        default: 8080
      path:
        description: Path where your Pi-hole's API is hosted
        default: api

paths:
  /auth:
    $ref: 'auth.yaml#/components/paths/auth'

  /stats/summary:
    $ref: 'stats.yaml#/components/paths/summary'

  /history:
    $ref: 'history.yaml#/components/paths/history'

  /history/clients:
    $ref: 'history.yaml#/components/paths/clients'

  /history/queries:
    $ref: 'history.yaml#/components/paths/queries'

  /dns/blocking:
    $ref: 'dns.yaml#/components/paths/blocking'

  /dns/cache:
    $ref: 'dns.yaml#/components/paths/cache'

  /domains/{type}/{kind}/{domain}:
    $ref: 'domains.yaml#/components/paths/type_kind_domain'

  /domains/{type}/{kind}:
    $ref: 'domains.yaml#/components/paths/type_kind'

  /groups/{name}:
    $ref: 'groups.yaml#/components/paths/name'

  /groups:
    $ref: 'groups.yaml#/components/paths/direct'

  /clients/{client}:
    $ref: 'clients.yaml#/components/paths/client'

  /clients:
    $ref: 'clients.yaml#/components/paths/direct'

  /lists/{list}:
    $ref: 'lists.yaml#/components/paths/list'

  /lists:
    $ref: 'lists.yaml#/components/paths/direct'

  /ftl/client:
    $ref: 'ftl.yaml#/components/paths/client'

  /ftl/logs/dns:
    $ref: 'ftl.yaml#/components/paths/logs/dns'

  /ftl/sysinfo:
    $ref: 'ftl.yaml#/components/paths/sysinfo'

  /ftl/dbinfo:
    $ref: 'ftl.yaml#/components/paths/dbinfo'

  /version:
    $ref: 'version.yaml#/components/paths/version'

components:
  securitySchemes:
    sid:
      type: apiKey
      name: sid
      description: SID used for secured endpoints
      in: header